# Generated by Django 2.1.1 on 2018-08-31 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='html',
            old_name='signature_code',
            new_name='unique_code',
        ),
        migrations.AddField(
            model_name='html',
            name='status',
            field=models.CharField(default='public', max_length=256),
        ),
        migrations.AlterField(
            model_name='html',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='html',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to=settings.AUTH_USER_MODEL),
        ),
    ]
